# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9edb996aabaad0f497e40834eee16e6d8fd914cc45c40297594fa0ae0319dc99f6411498c59d439a51556456b4400275f4fb555b376c4c43c85ac949df19cb45

test:
  secret_key_base: 7cf77bb784e213564fe78410c8cd5ae5c442b3fc09df62abcf9515ceaa05f76cc584f7d9806f486580052831573b7b728ccd73f50d8443e5496da1e142da5589

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
